# ==================== language block: any language ====================
# Everything language-specific the review scripts need. The driver calls only
# the LANG_* variables and lang_* functions defined here. This is the generic
# plugin's block: one row per language the language table above names, so a
# group of any of them is reviewed here when no plugin written for that
# language is installed. Which file is which language is the table, shared by
# every plugin; this block only says how each language writes a comment, a
# suppression directive and a test file.
#
# Contract:
#   LANG_NATIVE         the language ids this plugin reviews itself; a group of
#                       any other id is routed to the plugin that owns it
#   lang_configure <id> sets the variables below for that id; "custom" is the
#                       --glob override: a language the table does not know,
#                       reviewed with the broad row at the end;
#                       exit 2 for an id this block has no row for
#   LANG_EXCLUDE_RE     ERE over a relative path: directories never in scope
#   LANG_SUPPRESS_RE    ERE: a lint-suppression directive on a source line
#   LANG_COMMENT_RE     ERE: a source line that carries a comment (bracket
#                       expressions, no backslashes: the driver hands it to
#                       awk -v, which eats `\*` under gawk)
#   LANG_DIRECTIVE_RE   ERE: a comment line that is a directive, not prose
#   LANG_GENERATED_RE   ERE: a marker in a file's head that says it is generated
#   lang_is_test <path> exit 0 iff the path is a test file (--test-re overrides)
LANG_NATIVE="go python d rust c cpp java kotlin ruby shell typescript javascript csharp custom"
LANG_ID=""

lang_configure() {
  LANG_ID="$1"
  LANG_GENERATED_RE='Code generated .* DO NOT EDIT|DO NOT EDIT|@generated|automatically generated|Generated by'
  case "$1" in
    go)
      LANG_EXCLUDE_RE='(^|/)(vendor|\.git|testdata)/'
      LANG_SUPPRESS_RE='//nolint'
      LANG_COMMENT_RE='//'
      LANG_DIRECTIVE_RE='//(go:|nolint| Output:|line |export |extern )'
      ;;
    python)
      LANG_EXCLUDE_RE='(^|/)(\.venv|venv|\.git|node_modules|__pycache__|\.tox|build|dist)/'
      LANG_SUPPRESS_RE='#\s*(noqa|type:\s*ignore|ty:\s*ignore)'
      LANG_COMMENT_RE='(#|""")'
      LANG_DIRECTIVE_RE='#\s*(noqa|type:|ty:|pragma|fmt:|pylint:|ruff:|isort:|!)|>>>'
      ;;
    d)
      # D comments: // line, /* block */ and /+ nested +/. D-Scanner's
      # suppression is a comment: // @suppress(dscanner.<check>). A file's
      # inline `unittest` blocks test the production code beside them and keep
      # the file a production file; a test file is one under a test directory
      # or named *_test.d.
      LANG_EXCLUDE_RE='(^|/)(\.git|\.dub|vendor)/'
      LANG_SUPPRESS_RE='@suppress\('
      LANG_COMMENT_RE='(//|/[*]|/[+])'
      LANG_DIRECTIVE_RE='@suppress\(|dfmt (on|off)|#!'
      ;;
    rust)
      LANG_EXCLUDE_RE='(^|/)(\.git|target|vendor)/'
      LANG_SUPPRESS_RE='#!?\[allow\('
      LANG_COMMENT_RE='(//|/[*])'
      LANG_DIRECTIVE_RE='rustfmt::skip|clippy::'
      ;;
    c|cpp)
      LANG_EXCLUDE_RE='(^|/)(\.git|third_party|vendor)/'
      LANG_SUPPRESS_RE='NOLINT|cppcheck-suppress|#pragma (warning\s*\(\s*disable|GCC diagnostic ignored|clang diagnostic ignored)'
      LANG_COMMENT_RE='(//|/[*])'
      LANG_DIRECTIVE_RE='NOLINT|cppcheck-suppress|clang-format (on|off)|IWYU'
      ;;
    java|kotlin)
      LANG_EXCLUDE_RE='(^|/)(\.git|target|build|\.gradle)/'
      LANG_SUPPRESS_RE='@Suppress(Warnings)?\(|NOSONAR|noinspection|CHECKSTYLE:OFF|ktlint-disable|detekt:'
      LANG_COMMENT_RE='(//|/[*])'
      LANG_DIRECTIVE_RE='noinspection|CHECKSTYLE|NOSONAR|@formatter:|ktlint-|detekt:'
      ;;
    ruby)
      LANG_EXCLUDE_RE='(^|/)(\.git|vendor/bundle|tmp)/'
      LANG_SUPPRESS_RE='rubocop:disable|steep:ignore'
      LANG_COMMENT_RE='(#|=begin)'
      LANG_DIRECTIVE_RE='rubocop:|frozen_string_literal|encoding:|#!'
      ;;
    shell)
      LANG_EXCLUDE_RE='(^|/)(\.git)/'
      LANG_SUPPRESS_RE='shellcheck disable'
      LANG_COMMENT_RE='#'
      LANG_DIRECTIVE_RE='shellcheck|#!'
      ;;
    typescript|javascript)
      LANG_EXCLUDE_RE='(^|/)(\.git|node_modules|dist)/'
      LANG_SUPPRESS_RE='eslint-disable|@ts-(ignore|expect-error|nocheck)|biome-ignore'
      LANG_COMMENT_RE='(//|/[*])'
      LANG_DIRECTIVE_RE='eslint-|@ts-|prettier-ignore|biome-ignore|/// *<reference|#!'
      ;;
    csharp)
      LANG_EXCLUDE_RE='(^|/)(\.git|bin|obj)/'
      LANG_SUPPRESS_RE='#pragma warning disable|\[SuppressMessage'
      LANG_COMMENT_RE='(//|/[*])'
      LANG_DIRECTIVE_RE='ReSharper|#pragma'
      ;;
    custom)
      # A language the table does not know: every common comment marker and
      # suppression spelling, so --glob reviews it without a row of its own.
      LANG_EXCLUDE_RE='(^|/)(vendor|\.git|node_modules|\.venv|target|build|dist)/'
      LANG_SUPPRESS_RE='nolint|noqa|eslint-disable|#\[allow\(|@SuppressWarnings|type:\s*ignore|NOSONAR|rubocop:disable|shellcheck disable'
      LANG_COMMENT_RE='(//|#|/[*]|--|""")'
      LANG_DIRECTIVE_RE='//go:|nolint|#\s*(noqa|type:|pragma|!)|eslint-|@ts-|pragma'
      ;;
    *) return 2 ;;
  esac
  return 0
}

lang_is_test() {
  [[ -n "${OPT_TEST_RE:-}" ]] && { printf '%s\n' "$1" | grep -qE -- "$OPT_TEST_RE"; return; }
  case "$LANG_ID" in
    go) [[ "$1" == *_test.go ]] ;;
    python)
      case "$1" in
        *_test.py|test_*.py|*/test_*.py|conftest.py|*/conftest.py|tests/*|*/tests/*) return 0 ;;
      esac
      return 1 ;;
    d)
      case "$1" in
        *_test.d|test/*|*/test/*|tests/*|*/tests/*|testing/*|*/testing/*) return 0 ;;
      esac
      return 1 ;;
    rust)
      case "$1" in
        *_test.rs|tests/*|*/tests/*|benches/*|*/benches/*) return 0 ;;
      esac
      return 1 ;;
    java|kotlin)
      case "$1" in
        *Test.java|*Tests.java|*IT.java|*Test.kt|*Tests.kt|src/test/*|*/src/test/*|src/*Test/*|*/src/*Test/*) return 0 ;;
      esac
      return 1 ;;
    ruby)
      case "$1" in
        *_spec.rb|*_test.rb|spec/*|*/spec/*|test/*|*/test/*) return 0 ;;
      esac
      return 1 ;;
    csharp)
      case "$1" in
        *Test.cs|*Tests.cs|*.Tests/*|*/*.Tests/*|test/*|*/test/*|tests/*|*/tests/*) return 0 ;;
      esac
      return 1 ;;
    *)
      case "$1" in
        *_test.*|*.test.*|*.spec.*|*Test.*|test_*|*/test_*|test/*|*/test/*|tests/*|*/tests/*|spec/*|*/spec/*|__tests__/*|*/__tests__/*) return 0 ;;
      esac
      return 1 ;;
  esac
}
# ================== end language block: any language ==================
