package render_test

import (
	"testing"
	"testing/fstest"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/buzzdan/ai-coding-rules/tools/ldd-gen/internal/render"
)

const ruleR1 = `# R1 — Primitive Obsession

## Principle

Domain concepts in {{.Lang}} never travel raw; placement is ` + "`R4-helper-placement.md`" + `.

## Fix pattern

- **Replace Primitive with Domain Type**: introduce a parse function.
- **Over-abstraction found instead?** Apply the cheaper alternative.
- **A message chain is a placement signal, not a wrapper order**: guidance.
- **Extract Collection Type**: wrap the slice.

## Falsifying questions

{{include "rules/R1/questions.md"}}
`

const questionsR1 = `1. **Does the diff validate a primitive inline?**
   Detection: grep something.
2. **Is the same predicate enforced in more than one
   place?**
   Violation: two hits.
3. **Inverse — is a NEW type in the diff mere ceremony?**
`

const maxims = `# Maxims

### Tell, don't ask
— Andy Hunt & Dave Thomas

**Ask:** what will the caller *do* with the value —
and does that decision belong on the type?

**Compiled into:** R11.

### Make the zero value useful

**Ask:** could ` + "`var x T`" + ` just work?
`

const houseRules = `### G1 — Package names

Prose.

**Review:** Does any package name a layer?

### G2 — Names

**Review:** Does any exported name repeat its package?
`

const handbook = `<!-- Generated by tools/ldd-gen -->
# {{.Lang}} Coding Rules
- {{maxim "Tell, don't ask"}}
- {{maxim "Make the zero value useful"}}
{{section "rules/R1.md" "Principle"}}
{{include "handbook/R1/example.md"}}
**Moves:** {{moves "rules/R1.md"}}
- **R1** {{questions "rules/R1/questions.md" 1 2}}
- **All** {{questions "rules/R1/questions.md"}}
- **House** {{reviews "handbook/house-rules.md"}}
`

func handbookCore() fstest.MapFS {
	return fstest.MapFS{
		"rules/R1.md":                    {Data: []byte(ruleR1)},
		"includes/rules/R1/questions.md": {Data: []byte(questionsR1)},
		"maxims.md":                      {Data: []byte(maxims)},
		"handbook/coding-rules.md":       {Data: []byte(handbook)},
	}
}

func TestHandbook(t *testing.T) {
	t.Parallel()
	b := lang(t, fstest.MapFS{
		"handbook/R1/example.md":  {Data: []byte("```p\ncode in {{.Lang}}\n```\n")},
		"handbook/house-rules.md": {Data: []byte(houseRules)},
	})
	out, err := render.Handbook(handbookCore(), b)
	require.NoError(t, err)
	want := `<!-- Generated by tools/ldd-gen -->
# Lang Coding Rules
- **Tell, don't ask.** What will the caller *do* with the value — and does that decision belong on the type?
- **Make the zero value useful.** Could ` + "`var x T`" + ` just work?
Domain concepts in Lang never travel raw; placement is R4.
` + "```p\ncode in Lang\n```" + `
**Moves:** Replace Primitive with Domain Type · Extract Collection Type
- **R1** Does the diff validate a primitive inline? · Is the same predicate enforced in more than one place?
- **All** Does the diff validate a primitive inline? · Is the same predicate enforced in more than one place? · Inverse — is a NEW type in the diff mere ceremony?
- **House** Does any package name a layer? · Does any exported name repeat its package?
`
	assert.Equal(t, want, string(out))
}

func TestHandbook_ReadsBindingOverrides(t *testing.T) {
	t.Parallel()
	b := lang(t, fstest.MapFS{
		"handbook/R1/example.md":  {Data: []byte("x\n")},
		"handbook/house-rules.md": {Data: []byte(houseRules)},
		"overrides/rules/R1.md":   {Data: []byte("## Principle\n\nOverridden for {{.Lang}}.\n\n## Fix pattern\n\n- **Own Move**: theirs.\n")},
		"overrides/maxims.md":     {Data: []byte("### Tell, don't ask\n\n**Ask:** overridden ask?\n\n### Make the zero value useful\n\n**Ask:** still here?\n")},
	})
	out, err := render.Handbook(handbookCore(), b)
	require.NoError(t, err)
	assert.Contains(t, string(out), "Overridden for Lang.", "section reads the override the plugin ships")
	assert.Contains(t, string(out), "**Moves:** Own Move", "moves reads the override")
	assert.Contains(t, string(out), "**Tell, don't ask.** Overridden ask?", "maxim reads the override")
}

func TestHandbook_StaysOutOfThePluginTree(t *testing.T) {
	t.Parallel()
	tree, err := render.Render(handbookCore(), lang(t, nil))
	require.NoError(t, err)
	_, rendered := tree["handbook/coding-rules.md"]
	assert.False(t, rendered, "the handbook template is never a plugin file")
	assert.Contains(t, tree, "rules/R1.md")
}

func TestHandbook_Errors(t *testing.T) {
	t.Parallel()
	valid := fstest.MapFS{
		"handbook/R1/example.md":  {Data: []byte("x\n")},
		"handbook/house-rules.md": {Data: []byte(houseRules)},
	}
	cases := []struct {
		name     string
		template string
		want     string
	}{
		{name: "missing marker", template: "# no marker\n", want: "must begin with"},
		{name: "unknown section", template: "<!-- Generated by tools/ldd-gen -->\n{{section \"rules/R1.md\" \"Nope\"}}\n", want: `no "## Nope" heading`},
		{name: "unknown core file", template: "<!-- Generated by tools/ldd-gen -->\n{{section \"rules/R99.md\" \"Principle\"}}\n", want: "core rules/R99.md"},
		{name: "unknown question", template: "<!-- Generated by tools/ldd-gen -->\n{{questions \"rules/R1/questions.md\" 7}}\n", want: "no question 7"},
		{name: "unknown maxim", template: "<!-- Generated by tools/ldd-gen -->\n{{maxim \"Nope\"}}\n", want: `maxim "Nope"`},
		{name: "no review line", template: "<!-- Generated by tools/ldd-gen -->\n{{reviews \"handbook/R1/example.md\"}}\n", want: "no **Review:** line"},
		{name: "no fix pattern", template: "<!-- Generated by tools/ldd-gen -->\n{{moves \"maxims.md\"}}\n", want: `no "## Fix pattern" heading`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			core := handbookCore()
			core["handbook/coding-rules.md"] = &fstest.MapFile{Data: []byte(tc.template)}
			_, err := render.Handbook(core, lang(t, valid))
			require.Error(t, err)
			assert.Contains(t, err.Error(), tc.want)
		})
	}
}

func TestHandbook_NoTemplateIsAnError(t *testing.T) {
	t.Parallel()
	_, err := render.Handbook(fstest.MapFS{}, lang(t, nil))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "handbook:")
}
