package render

import (
	"fmt"
	"io/fs"
	"regexp"
	"strings"
	"text/template"

	"github.com/buzzdan/ai-coding-rules/tools/ldd-gen/internal/binding"
)

// The handbook is the standalone coding-rules document a team reads without
// the plugin. Its one template lives under core/handbook/ and is rendered to
// the path the profile's handbook key names, never into the plugin tree.
const (
	handbookDir      = "handbook"
	handbookTemplate = "handbook/coding-rules.md"
	// HandbookMarker opens every rendered handbook. Generate refuses to
	// overwrite a file at the handbook path that does not start with it, so a
	// hand-written document can never be replaced by mistake.
	HandbookMarker = "<!-- Generated by tools/ldd-gen"
)

// Handbook renders core/handbook/coding-rules.md through the binding.
// Besides {{include}}, the handbook template may call five extraction
// functions that read the rules the plugin already carries, so the handbook
// restates nothing: section, moves, questions, maxim and reviews (see
// core/README.md, "The handbook").
func Handbook(core fs.FS, b binding.Binding) ([]byte, error) {
	src, err := fs.ReadFile(core, handbookTemplate)
	if err != nil {
		return nil, fmt.Errorf("handbook: %w", err)
	}
	r := &renderer{core: core, binding: b}
	out, err := r.executeWith(handbookTemplate, string(src), r.handbookFuncs())
	if err != nil {
		return nil, err
	}
	if !strings.HasPrefix(string(out), HandbookMarker) {
		return nil, fmt.Errorf("handbook: the rendering must begin with %q", HandbookMarker)
	}
	return out, nil
}

func (r *renderer) handbookFuncs() template.FuncMap {
	return template.FuncMap{
		"include":   r.include,
		"section":   r.section,
		"moves":     r.moves,
		"questions": r.questions,
		"maxim":     r.maxim,
		"reviews":   r.reviews,
	}
}

// section returns the body of one "## Heading" section of a core file,
// rendered through the binding, with references to sibling rule files
// (`R2-self-validating-types.md`) shortened to the rule's number, since the
// handbook reader has no rule files beside it.
func (r *renderer) section(corePath, heading string) (string, error) {
	body, err := r.renderedCore(corePath)
	if err != nil {
		return "", err
	}
	text, ok := sectionBody(body, heading)
	if !ok {
		return "", fmt.Errorf("section %q: %s has no \"## %s\" heading", heading, corePath, heading)
	}
	return ruleFileRef.ReplaceAllString(text, "$1"), nil
}

var ruleFileRef = regexp.MustCompile("`(R[0-9]+)-[a-z0-9-]+\\.md`")

// moves lists the refactoring moves a rule's Fix pattern section names, joined
// with " · ". A bullet's bold lead is a move name when it reads as a catalogue
// entry; a lead that is a sentence (opens with an article, carries a comma or
// ends in punctuation) is guidance and is left out.
func (r *renderer) moves(corePath string) (string, error) {
	body, err := r.renderedCore(corePath)
	if err != nil {
		return "", err
	}
	fix, ok := sectionBody(body, "Fix pattern")
	if !ok {
		return "", fmt.Errorf("moves: %s has no \"## Fix pattern\" heading", corePath)
	}
	var names []string
	for _, lead := range boldLeads(fix, "- ") {
		if isMoveName(lead) {
			names = append(names, lead)
		}
	}
	if len(names) == 0 {
		return "", fmt.Errorf("moves: %s names no move", corePath)
	}
	return strings.Join(names, " · "), nil
}

func isMoveName(lead string) bool {
	lower := strings.ToLower(lead)
	for _, article := range []string{"a ", "an ", "the "} {
		if strings.HasPrefix(lower, article) {
			return false
		}
	}
	return !strings.Contains(lead, ",") && !strings.HasSuffix(lead, "?") && !strings.HasSuffix(lead, ".")
}

// questions returns the bold headlines of the numbered falsifying questions in
// an include file — the binding's own, else the core default — joined with
// " · ". With numbers given, only those questions are kept, in the order
// given; a number the file does not carry is an error, so a renumbered
// question file is noticed rather than silently rendering its neighbour.
func (r *renderer) questions(includeName string, nums ...int) (string, error) {
	body, err := r.include(includeName)
	if err != nil {
		return "", err
	}
	all := numberedHeadlines(body)
	if len(all) == 0 {
		return "", fmt.Errorf("questions %q: no numbered bold headline found", includeName)
	}
	if len(nums) == 0 {
		return joinValues(all), nil
	}
	picked := make([]string, 0, len(nums))
	for _, n := range nums {
		headline, ok := all[n]
		if !ok {
			return "", fmt.Errorf("questions %q: no question %d", includeName, n)
		}
		picked = append(picked, headline)
	}
	return strings.Join(picked, " · "), nil
}

// maxim returns one maxim from core/maxims.md as a handbook bullet body:
// "**<title>.** <its Ask paragraph>". The title must match a "### " heading.
func (r *renderer) maxim(title string) (string, error) {
	body, err := r.renderedCore("maxims.md")
	if err != nil {
		return "", err
	}
	ask, ok := maximAsk(body, title)
	if !ok {
		return "", fmt.Errorf("maxim %q: no such heading with an **Ask:** paragraph in maxims.md", title)
	}
	return "**" + title + ".** " + capitalize(ask), nil
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// reviews returns the "**Review:**" lines of a house-rules include joined with
// " · ": each house rule ends with the one question a reviewer asks for it.
func (r *renderer) reviews(includeName string) (string, error) {
	body, err := r.include(includeName)
	if err != nil {
		return "", err
	}
	var lines []string
	for _, line := range strings.Split(body, "\n") {
		if q, ok := strings.CutPrefix(strings.TrimSpace(line), "**Review:**"); ok {
			lines = append(lines, strings.TrimSpace(q))
		}
	}
	if len(lines) == 0 {
		return "", fmt.Errorf("reviews %q: no **Review:** line", includeName)
	}
	return strings.Join(lines, " · "), nil
}

// renderedCore reads a core file and renders it through the binding, so the
// text the extraction functions see is what the plugin ships.
func (r *renderer) renderedCore(corePath string) (string, error) {
	src, err := fs.ReadFile(r.core, corePath)
	if err != nil {
		return "", fmt.Errorf("core %s: %w", corePath, err)
	}
	out, err := r.execute(corePath, string(src))
	if err != nil {
		return "", err
	}
	return string(out), nil
}
