# ===================== language block: ts-react =====================
# Everything language-specific the review scripts need. The driver calls only
# the LANG_* variables and lang_* functions defined here; a build of the script
# for another language replaces this block and nothing else.
#
# Contract:
#   LANG_SRC_GLOB       find(1) -name pattern for the language's source files
#   LANG_EXCLUDE_RE     ERE over a relative path: directories never in scope
#   LANG_SUPPRESS_RE    ERE: a lint-suppression directive on a source line
#   LANG_COMMENT_RE     ERE: a source line that carries a comment
#                       (bracket expressions, no backslashes: the driver hands it to
#                       awk -v, which eats `\*` and `\s` under gawk)
#   LANG_DIRECTIVE_RE   ERE: a comment line that is a directive, not prose
#   LANG_GENERATED_RE   ERE: a marker in a file's head that says it is generated
#   lang_configure      reads OPT_GLOB / OPT_TEST_RE (set by --glob / --test-re)
#   lang_is_test <path> exit 0 iff the path is a test file
#
# One glob has to cover `.ts` and `.tsx` (the driver passes it to find -name, a
# case pattern and git pathspecs alike), so it is `*.ts*`; the names that glob
# also admits — declaration files, source maps, `tsconfig.tsbuildinfo`, Vitest
# snapshots, `.tsv` data — and the `*.generated.ts(x)` modules a code generator
# writes are dropped by the exclude pattern, which the driver applies to every
# candidate path after the glob.
LANG_SRC_GLOB='*.ts*'
LANG_EXCLUDE_RE='(^|/)(node_modules|dist|build|\.next|coverage|\.git|storybook-static)/|\.d\.ts$|\.generated\.tsx?$|\.tsbuildinfo$|\.map$|\.snap$|\.tsv$'
LANG_SUPPRESS_RE='eslint-disable(-next-line|-line)?|@ts-(expect-error|ignore|nocheck)|prettier-ignore'
LANG_COMMENT_RE='//|/[*]|^[[:space:]]*[*]'
LANG_DIRECTIVE_RE='eslint-(disable|enable)|@ts-(expect-error|ignore|nocheck|check)|prettier-ignore|/// <reference|@vitest-environment|istanbul ignore|c8 ignore|biome-ignore'
LANG_GENERATED_RE='Generated by|DO NOT EDIT|@generated|automatically generated'

lang_configure() {
  [[ -n "${OPT_GLOB:-}" ]] && LANG_SRC_GLOB="$OPT_GLOB"
  return 0
}

# Stories (`*.stories.tsx`) are not production code either: Storybook renders
# them, nothing ships them, so their sleeps and doubles are judged as a test's.
lang_is_test() {
  [[ -n "${OPT_TEST_RE:-}" ]] && { printf '%s\n' "$1" | grep -qE -- "$OPT_TEST_RE"; return; }
  case "$1" in
    *.test.ts|*.test.tsx|*.spec.ts|*.spec.tsx|*.stories.tsx) return 0 ;;
    __tests__/*|*/__tests__/*|test-utils/*|*/test-utils/*|tests/*|*/tests/*|e2e/*|*/e2e/*) return 0 ;;
  esac
  return 1
}
# =================== end language block: ts-react ===================
